package com.daaw;

import com.daaw.xb;
/* loaded from: classes.dex */
public final class uz2 {
    public static final xb a;
    public static final xb b;
    public static final xb c;
    public static final xb d;
    public static final xb e;
    public static final xb f;
    public static final xb g;
    public static final xb h;
    public static final xb i;
    public static final xb j;
    public static final xb k;
    public static final xb l;
    public static final xb m;
    public static final xb n;
    public static final xb o;
    public static final xb p;
    public static final xb q;
    public static final xb r;
    public static final xb s;
    public static final xb t;
    public static final xb u;
    public static final xb v;
    public static final xb w;
    public static final xb x;
    public static final xb y;

    static {
        xb.a c2 = xb.c();
        c2.c(3);
        c2.b("Google Play In-app Billing API version is less than 3");
        a = c2.a();
        xb.a c3 = xb.c();
        c3.c(3);
        c3.b("Google Play In-app Billing API version is less than 9");
        b = c3.a();
        xb.a c4 = xb.c();
        c4.c(3);
        c4.b("Billing service unavailable on device.");
        c = c4.a();
        xb.a c5 = xb.c();
        c5.c(5);
        c5.b("Client is already in the process of connecting to billing service.");
        d = c5.a();
        xb.a c6 = xb.c();
        c6.c(5);
        c6.b("The list of SKUs can't be empty.");
        e = c6.a();
        xb.a c7 = xb.c();
        c7.c(5);
        c7.b("SKU type can't be empty.");
        f = c7.a();
        xb.a c8 = xb.c();
        c8.c(5);
        c8.b("Product type can't be empty.");
        g = c8.a();
        xb.a c9 = xb.c();
        c9.c(-2);
        c9.b("Client does not support extra params.");
        h = c9.a();
        xb.a c10 = xb.c();
        c10.c(5);
        c10.b("Invalid purchase token.");
        i = c10.a();
        xb.a c11 = xb.c();
        c11.c(6);
        c11.b("An internal error occurred.");
        j = c11.a();
        xb.a c12 = xb.c();
        c12.c(5);
        c12.b("SKU can't be null.");
        k = c12.a();
        xb.a c13 = xb.c();
        c13.c(0);
        l = c13.a();
        xb.a c14 = xb.c();
        c14.c(-1);
        c14.b("Service connection is disconnected.");
        m = c14.a();
        xb.a c15 = xb.c();
        c15.c(-3);
        c15.b("Timeout communicating with service.");
        n = c15.a();
        xb.a c16 = xb.c();
        c16.c(-2);
        c16.b("Client does not support subscriptions.");
        o = c16.a();
        xb.a c17 = xb.c();
        c17.c(-2);
        c17.b("Client does not support subscriptions update.");
        p = c17.a();
        xb.a c18 = xb.c();
        c18.c(-2);
        c18.b("Client does not support get purchase history.");
        q = c18.a();
        xb.a c19 = xb.c();
        c19.c(-2);
        c19.b("Client does not support price change confirmation.");
        r = c19.a();
        xb.a c20 = xb.c();
        c20.c(-2);
        c20.b("Play Store version installed does not support cross selling products.");
        s = c20.a();
        xb.a c21 = xb.c();
        c21.c(-2);
        c21.b("Client does not support multi-item purchases.");
        t = c21.a();
        xb.a c22 = xb.c();
        c22.c(-2);
        c22.b("Client does not support offer_id_token.");
        u = c22.a();
        xb.a c23 = xb.c();
        c23.c(-2);
        c23.b("Client does not support ProductDetails.");
        v = c23.a();
        xb.a c24 = xb.c();
        c24.c(-2);
        c24.b("Client does not support in-app messages.");
        w = c24.a();
        xb.a c25 = xb.c();
        c25.c(-2);
        c25.b("Client does not support alternative billing.");
        x = c25.a();
        xb.a c26 = xb.c();
        c26.c(5);
        c26.b("Unknown feature");
        y = c26.a();
    }
}
