package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import androidx.recyclerview.widget.ItemTouchHelper;
import com.google.android.exoplayer2.DefaultRenderersFactory;
import com.google.android.exoplayer2.source.chunk.ChunkedTrackBlacklistUtil;
import com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection;
import com.mpatric.mp3agic.MpegFrame;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;
@zzadh
/* loaded from: classes2.dex */
public final class zznk {
    private static final zzna<String> zzaua = zzna.zza(0, "gads:sdk_core_experiment_id");
    public static final zzna<String> zzaub = zzna.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    private static final zzna<String> zzauc = zzna.zza(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static final zzna<Boolean> zzaud = zzna.zza(0, "gads:request_builder:singleton_webview", (Boolean) false);
    private static final zzna<String> zzaue = zzna.zza(0, "gads:request_builder:singleton_webview_experiment_id");
    private static final zzna<Boolean> zzauf = zzna.zza(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    private static final zzna<String> zzaug = zzna.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzna<Boolean> zzauh = zzna.zza(0, "gads:sdk_crash_report_enabled", (Boolean) false);
    public static final zzna<Boolean> zzaui = zzna.zza(0, "gads:report_dynamite_crash_in_background_thread", (Boolean) false);
    public static final zzna<Boolean> zzauj = zzna.zza(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    public static final zzna<String> zzauk = zzna.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzna<Float> zzaul = zzna.zza(1, "gads:trapped_exception_sample_rate", 0.01f);
    public static final zzna<Boolean> zzaum = zzna.zza(0, "gads:block_autoclicks", (Boolean) false);
    private static final zzna<String> zzaun = zzna.zza(0, "gads:block_autoclicks_experiment_id");
    private static final zzna<String> zzauo = zzna.zza(0, "gads:spam_app_context:experiment_id");
    private static final zzna<Integer> zzaup = zzna.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzna<String> zzauq = zzna.zza(1, "gads:video_exo_player:version", "1");
    public static final zzna<Integer> zzaur = zzna.zza(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzna<Integer> zzaus = zzna.zza(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzna<Integer> zzaut = zzna.zza(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final zzna<Integer> zzauu = zzna.zza(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final zzna<Integer> zzauv = zzna.zza(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    private static final zzna<String> zzauw = zzna.zza(0, "gads:video_stream_cache:experiment_id");
    public static final zzna<Integer> zzaux = zzna.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzna<Integer> zzauy = zzna.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzna<Integer> zzauz = zzna.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzna<Long> zzava = zzna.zza(1, "gads:video_stream_cache:limit_time_sec", 300L);
    public static final zzna<Long> zzavb = zzna.zza(1, "gads:video_stream_cache:notify_interval_millis", 125L);
    public static final zzna<Integer> zzavc = zzna.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzna<Boolean> zzavd = zzna.zza(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final zzna<String> zzave = zzna.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzna<Long> zzavf = zzna.zza(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    public static final zzna<Boolean> zzavg = zzna.zza(1, "gads:video:force_watermark", (Boolean) false);
    public static final zzna<Long> zzavh = zzna.zza(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    public static final zzna<Boolean> zzavi = zzna.zza(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final zzna<Integer> zzavj = zzna.zza(1, "gads:video:spinner:scale", 4);
    public static final zzna<Long> zzavk = zzna.zza(1, "gads:video:spinner:jank_threshold_ms", 50L);
    public static final zzna<Boolean> zzavl = zzna.zza(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final zzna<Boolean> zzavm = zzna.zza(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final zzna<Boolean> zzavn = zzna.zza(1, "gads:memory_bundle:runtime_info", (Boolean) true);
    public static final zzna<String> zzavo = zzna.zza(1, "gads:video:codec_query_mime_types", "");
    public static final zzna<Integer> zzavp = zzna.zza(1, "gads:video:codec_query_minimum_version", 16);
    private static final zzna<Boolean> zzavq = zzna.zza(0, "gads:ad_id_app_context:enabled", (Boolean) false);
    private static final zzna<Float> zzavr = zzna.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static final zzna<String> zzavs = zzna.zza(0, "gads:ad_id_app_context:experiment_id");
    private static final zzna<String> zzavt = zzna.zza(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static final zzna<Boolean> zzavu = zzna.zza(0, "gads:ad_id_use_shared_preference:enabled", (Boolean) false);
    private static final zzna<Float> zzavv = zzna.zza(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static final zzna<Boolean> zzavw = zzna.zza(0, "gads:ad_id_use_persistent_service:enabled", (Boolean) false);
    private static final zzna<Boolean> zzavx = zzna.zza(0, "gads:ad_id:use_ipc:enabled", (Boolean) false);
    private static final zzna<String> zzavy = zzna.zzb(0, "gads:looper_for_gms_client:experiment_id");
    public static final zzna<Boolean> zzavz = zzna.zza(0, "gads:looper_for_gms_client:enabled", (Boolean) true);
    public static final zzna<Boolean> zzawa = zzna.zza(0, "gads:sw_ad_request_service:enabled", (Boolean) true);
    private static final zzna<Boolean> zzawb = zzna.zza(0, "gads:sw_dynamite:enabled", (Boolean) true);
    public static final zzna<String> zzawc = zzna.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzna<String> zzawd = zzna.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzna<String> zzawe = zzna.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzna<String> zzawf = zzna.zza(1, "gad:mraid:version", "2.0");
    public static final zzna<Boolean> zzawg = zzna.zza(1, "gads:mraid:unload", (Boolean) false);
    public static final zzna<Boolean> zzawh = zzna.zza(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final zzna<String> zzawi = zzna.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzna<Boolean> zzawj = zzna.zza(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final zzna<Boolean> zzawk = zzna.zza(0, "gads:enable_content_fetching", (Boolean) true);
    public static final zzna<Integer> zzawl = zzna.zza(0, "gads:content_length_weight", 1);
    public static final zzna<Integer> zzawm = zzna.zza(0, "gads:content_age_weight", 1);
    public static final zzna<Integer> zzawn = zzna.zza(0, "gads:min_content_len", 11);
    public static final zzna<Integer> zzawo = zzna.zza(0, "gads:fingerprint_number", 10);
    public static final zzna<Integer> zzawp = zzna.zza(0, "gads:sleep_sec", 10);
    public static final zzna<Boolean> zzawq = zzna.zza(1, "gads:enable_content_url_hash", (Boolean) true);
    public static final zzna<Integer> zzawr = zzna.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzna<Boolean> zzaws = zzna.zza(1, "gads:enable_content_vertical_hash", (Boolean) true);
    public static final zzna<Integer> zzawt = zzna.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzna<Integer> zzawu = zzna.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzna<String> zzawv = zzna.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzna<String> zzaww = zzna.zza(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzna<Boolean> zzawx = zzna.zza(0, "gad:app_index_enabled", (Boolean) true);
    public static final zzna<Boolean> zzawy = zzna.zza(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    public static final zzna<Boolean> zzawz = zzna.zza(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    public static final zzna<Long> zzaxa = zzna.zza(0, "gads:app_index:timeout_ms", 1000L);
    private static final zzna<String> zzaxb = zzna.zza(0, "gads:app_index:experiment_id");
    private static final zzna<String> zzaxc = zzna.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final zzna<Boolean> zzaxd = zzna.zza(0, "gads:kitkat_interstitial_workaround:enabled", (Boolean) true);
    public static final zzna<Boolean> zzaxe = zzna.zza(0, "gads:interstitial_follow_url", (Boolean) true);
    public static final zzna<Boolean> zzaxf = zzna.zza(0, "gads:interstitial_follow_url:register_click", (Boolean) true);
    private static final zzna<String> zzaxg = zzna.zza(0, "gads:interstitial_follow_url:experiment_id");
    private static final zzna<Boolean> zzaxh = zzna.zza(0, "gads:analytics_enabled", (Boolean) true);
    public static final zzna<Boolean> zzaxi = zzna.zza(0, "gads:ad_key_enabled", (Boolean) false);
    public static final zzna<Boolean> zzaxj = zzna.zza(1, "gads:sai:enabled", (Boolean) true);
    public static final zzna<Boolean> zzaxk = zzna.zza(1, "gads:sai:banner_ad_enabled", (Boolean) true);
    public static final zzna<Boolean> zzaxl = zzna.zza(1, "gads:sai:native_ad_enabled", (Boolean) true);
    public static final zzna<Boolean> zzaxm = zzna.zza(1, "gads:sai:interstitial_ad_enabled", (Boolean) true);
    public static final zzna<Boolean> zzaxn = zzna.zza(1, "gads:sai:rewardedvideo_ad_enabled", (Boolean) true);
    public static final zzna<String> zzaxo = zzna.zza(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzna<String> zzaxp = zzna.zza(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final zzna<Boolean> zzaxq = zzna.zza(1, "gads:sai:click_gmsg_enabled", (Boolean) true);
    public static final zzna<Boolean> zzaxr = zzna.zza(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final zzna<String> zzaxs = zzna.zza(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzna<Long> zzaxt = zzna.zza(1, "gads:sai:timeout_ms", -1L);
    public static final zzna<Integer> zzaxu = zzna.zza(1, "gads:sai:scion_thread_pool_size", 5);
    public static final zzna<Boolean> zzaxv = zzna.zza(1, "gads:x_seconds_rewarded:enable", (Boolean) false);
    private static final zzna<Integer> zzaxw = zzna.zza(0, "gads:webview_cache_version", 0);
    public static final zzna<Boolean> zzaxx = zzna.zza(1, "gads:webview:ignore_over_scroll", (Boolean) true);
    public static final zzna<Boolean> zzaxy = zzna.zza(0, "gads:corewebview:adwebview_factory:enable", (Boolean) false);
    public static final zzna<Boolean> zzaxz = zzna.zza(0, "gads:corewebview:javascript_engine", (Boolean) false);
    public static final zzna<Boolean> zzaya = zzna.zza(1, "gad:webview:inject_scripts", (Boolean) false);
    public static final zzna<Boolean> zzayb = zzna.zza(0, "gads:webview:permission:disabled", (Boolean) false);
    private static final zzna<String> zzayc = zzna.zzb(0, "gads:pan:experiment_id");
    public static final zzna<Boolean> zzayd = zzna.zza(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    public static final zzna<Long> zzaye = zzna.zza(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    public static final zzna<Boolean> zzayf = zzna.zza(1, "gads:rewarded:ad_metadata_enabled", (Boolean) false);
    public static final zzna<Boolean> zzayg = zzna.zza(1, "gads:app_activity_tracker:enabled", (Boolean) true);
    public static final zzna<Long> zzayh = zzna.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    public static final zzna<Long> zzayi = zzna.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzna<Boolean> zzayj = zzna.zza(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final zzna<Long> zzayk = zzna.zza(1, "gads:adid_values_in_adrequest:timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<Boolean> zzayl = zzna.zza(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    public static final zzna<Boolean> zzaym = zzna.zza(1, "gads:enable_ad_loader_manager", (Boolean) true);
    private static final zzna<Boolean> zzayn = zzna.zza(0, "gads:ad_serving:enabled", (Boolean) true);
    public static final zzna<Boolean> zzayo = zzna.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", (Boolean) true);
    public static final zzna<Boolean> zzayp = zzna.zza(1, "gads:ad_manager:admob_extra:new_bundle", (Boolean) true);
    public static final zzna<Long> zzayq = zzna.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzna<Boolean> zzayr = zzna.zza(1, "gads:interstitial_ad_immersive_mode", (Boolean) true);
    public static final zzna<Boolean> zzays = zzna.zza(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    public static final zzna<Boolean> zzayt = zzna.zza(1, "gads:disabling_closable_area:enabled", (Boolean) false);
    private static final zzna<Boolean> zzayu = zzna.zza(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static final zzna<String> zzayv = zzna.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final zzna<Integer> zzayw = zzna.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static final zzna<Integer> zzayx = zzna.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzna<Boolean> zzayy = zzna.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final zzna<Boolean> zzayz = zzna.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final zzna<String> zzaza = zzna.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzna<String> zzazb = zzna.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzna<Integer> zzazc = zzna.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzna<Integer> zzazd = zzna.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzna<Integer> zzaze = zzna.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzna<String> zzazf = zzna.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final zzna<Integer> zzazg = zzna.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final zzna<Integer> zzazh = zzna.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final zzna<Long> zzazi = zzna.zza(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
    public static final zzna<Long> zzazj = zzna.zza(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
    public static final zzna<Float> zzazk = zzna.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final zzna<Float> zzazl = zzna.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final zzna<Boolean> zzazm = zzna.zza(0, "gads:debug_logging_feature:enable", (Boolean) false);
    public static final zzna<Boolean> zzazn = zzna.zza(0, "gads:debug_logging_feature:intercept_web_view", (Boolean) false);
    private static final zzna<Integer> zzazo = zzna.zza(1, "gads:heap_wastage:bytes", 0);
    public static final zzna<String> zzazp = zzna.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzna<String> zzazq = zzna.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzna<Boolean> zzazr = zzna.zza(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final zzna<Boolean> zzazs = zzna.zza(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final zzna<Long> zzazt = zzna.zza(1, "gads:position_watcher:throttle_ms", 200L);
    public static final zzna<Boolean> zzazu = zzna.zza(1, "gads:include_lock_screen_apps_for_visibility", (Boolean) true);
    public static final zzna<Boolean> zzazv = zzna.zza(0, "gads:device_info_caching:enabled", (Boolean) true);
    public static final zzna<Long> zzazw = zzna.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    public static final zzna<Boolean> zzazx = zzna.zza(1, "gads:gen204_signals:enabled", (Boolean) false);
    public static final zzna<Boolean> zzazy = zzna.zza(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    private static final zzna<Boolean> zzazz = zzna.zza(0, "gads:adid_reporting:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbaa = zzna.zza(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbab = zzna.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbac = zzna.zza(0, "gads:request_pkg:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbad = zzna.zza(1, "gads:gmsg:disable_back_button:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbae = zzna.zza(0, "gads:gmsg:video_meta:enabled", (Boolean) true);
    private static final zzna<String> zzbaf = zzna.zza(0, "gads:gmsg:video_meta:experiment_id");
    private static final zzna<Long> zzbag = zzna.zza(1, "gads:network:cache_prediction_duration_s", 300L);
    public static final zzna<Long> zzbah = zzna.zza(1, "gads:network:network_prediction_timeout_ms", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<Boolean> zzbai = zzna.zza(0, "gads:mediation:dynamite_first:admobadapter", (Boolean) true);
    public static final zzna<Boolean> zzbaj = zzna.zza(0, "gads:mediation:dynamite_first:adurladapter", (Boolean) true);
    public static final zzna<Boolean> zzbak = zzna.zza(1, "gads:bypass_adrequest_service_for_inlined_mediation", (Boolean) true);
    private static final zzna<Long> zzbal = zzna.zza(1, "gads:rtb_signal_timeout_ms", 1000L);
    public static final zzna<Long> zzbam = zzna.zza(0, "gads:resolve_future:default_timeout_ms", 30000L);
    public static final zzna<Long> zzban = zzna.zza(0, "gads:ad_loader:timeout_ms", (long) ChunkedTrackBlacklistUtil.DEFAULT_TRACK_BLACKLIST_MS);
    public static final zzna<Long> zzbao = zzna.zza(0, "gads:rendering:timeout_ms", (long) ChunkedTrackBlacklistUtil.DEFAULT_TRACK_BLACKLIST_MS);
    public static final zzna<Boolean> zzbap = zzna.zza(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final zzna<Long> zzbaq = zzna.zza(1, "gads:gestures:task_timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<Boolean> zzbar = zzna.zza(1, "gads:gestures:asig:enabled", (Boolean) false);
    public static final zzna<Boolean> zzbas = zzna.zza(1, "gads:gestures:ans:enabled", (Boolean) false);
    public static final zzna<Boolean> zzbat = zzna.zza(1, "gads:gestures:tos:enabled", (Boolean) false);
    public static final zzna<Boolean> zzbau = zzna.zza(1, "gads:signal:app_permissions:disabled", (Boolean) false);
    public static final zzna<Boolean> zzbav = zzna.zza(1, "gads:gestures:inthex:enabled", (Boolean) false);
    public static final zzna<Boolean> zzbaw = zzna.zza(1, "gads:gestures:hpk:enabled", (Boolean) true);
    public static final zzna<String> zzbax = zzna.zza(1, "gads:gestures:pk", "");
    public static final zzna<Boolean> zzbay = zzna.zza(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbaz = zzna.zza(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final zzna<Boolean> zzbba = zzna.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbbb = zzna.zza(0, "gass:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbbc = zzna.zza(0, "gass:enable_int_signal", (Boolean) true);
    public static final zzna<Boolean> zzbbd = zzna.zza(0, "gass:enable_ad_attestation_signal", (Boolean) true);
    private static final zzna<Boolean> zzbbe = zzna.zza(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    private static final zzna<Boolean> zzbbf = zzna.zza(0, "gads:edu_device_helper:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbbg = zzna.zza(0, "gads:support_screen_shot", (Boolean) true);
    public static final zzna<Boolean> zzbbh = zzna.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", (Boolean) true);
    private static final zzna<String> zzbbi = zzna.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static final zzna<String> zzbbj = zzna.zza(1, "gads:sdk_core_constants:experiment_id");
    public static final zzna<String> zzbbk = zzna.zza(1, "gads:sdk_core_constants:caps", "");
    public static final zzna<Long> zzbbl = zzna.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzna<Boolean> zzbbm = zzna.zza(0, "gads:js_flags:mf", (Boolean) false);
    private static final zzna<Boolean> zzbbn = zzna.zza(1, "gads:js_flags:disable_phenotype", (Boolean) false);
    public static final zzna<Boolean> zzbbo = zzna.zza(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    public static final zzna<String> zzbbp = zzna.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static final zzna<String> zzbbq = zzna.zza(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static final zzna<String> zzbbr = zzna.zza(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzna<String> zzbbs = zzna.zza(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    private static final zzna<String> zzbbt = zzna.zza(1, "gads:singleton_webview_native:experiment_id");
    public static final zzna<Boolean> zzbbu = zzna.zza(1, "gads:enable_untrack_view_native", (Boolean) true);
    public static final zzna<Boolean> zzbbv = zzna.zza(1, "gads:ignore_untrack_view_google_native", (Boolean) true);
    public static final zzna<Boolean> zzbbw = zzna.zza(1, "gads:reset_listeners_preparead_native", (Boolean) true);
    public static final zzna<Integer> zzbbx = zzna.zza(1, "gads:native_video_load_timeout", 10);
    public static final zzna<Integer> zzbby = zzna.zza(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final zzna<String> zzbbz = zzna.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzna<Boolean> zzbca = zzna.zza(1, "gads:clamp_native_video_player_dimensions", (Boolean) true);
    public static final zzna<Boolean> zzbcb = zzna.zza(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final zzna<Boolean> zzbcc = zzna.zza(1, "gads:enable_singleton_broadcast_receiver", (Boolean) false);
    public static final zzna<Boolean> zzbcd = zzna.zza(1, "gads:native:overlay_new_fix:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbce = zzna.zza(1, "gads:native:count_impression_for_assets", (Boolean) false);
    public static final zzna<Boolean> zzbcf = zzna.zza(1, "gads:native:custom_one_point_five_click:enable", (Boolean) true);
    public static final zzna<Boolean> zzbcg = zzna.zza(1, "gads:unified_native_ad:enable", (Boolean) true);
    public static final zzna<Boolean> zzbch = zzna.zza(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    public static final zzna<Boolean> zzbci = zzna.zza(0, "gads:method_tracing:enabled", (Boolean) false);
    public static final zzna<Long> zzbcj = zzna.zza(0, "gads:method_tracing:duration_ms", 30000L);
    public static final zzna<Integer> zzbck = zzna.zza(0, "gads:method_tracing:count", 5);
    public static final zzna<Integer> zzbcl = zzna.zza(0, "gads:method_tracing:filesize", 134217728);
    private static final zzna<Boolean> zzbcm = zzna.zza(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static final zzna<String> zzbcn = zzna.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzna<Long> zzbco = zzna.zza(1, "gads:auto_location_timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    private static final zzna<String> zzbcp = zzna.zzb(1, "gads:auto_location_timeout:experiment_id");
    private static final zzna<Long> zzbcq = zzna.zza(1, "gads:auto_location_interval", -1L);
    private static final zzna<String> zzbcr = zzna.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzna<Boolean> zzbcs = zzna.zza(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    private static final zzna<String> zzbct = zzna.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzna<Long> zzbcu = zzna.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    private static final zzna<String> zzbcv = zzna.zza(0, "gads:afs:csa:experiment_id");
    public static final zzna<String> zzbcw = zzna.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzna<String> zzbcx = zzna.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzna<String> zzbcy = zzna.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzna<String> zzbcz = zzna.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzna<String> zzbda = zzna.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzna<Long> zzbdb = zzna.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    private static final zzna<Boolean> zzbdc = zzna.zza(0, "gads:afs:csa_ad_manager_enabled", (Boolean) true);
    private static final zzna<Boolean> zzbdd = zzna.zza(1, "gads:parental_controls:send_from_client", (Boolean) true);
    private static final zzna<Boolean> zzbde = zzna.zza(1, "gads:parental_controls:cache_results", (Boolean) true);
    public static final zzna<Long> zzbdf = zzna.zza(1, "gads:parental_controls:timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    private static final zzna<String> zzbdg = zzna.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static final zzna<Long> zzbdh = zzna.zza(0, "gads:safe_browsing:safety_net:delay_ms", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<Boolean> zzbdi = zzna.zza(0, "gads:safe_browsing:debug", (Boolean) false);
    public static final zzna<Boolean> zzbdj = zzna.zza(0, "gads:webview_cookie:enabled", (Boolean) true);
    private static final zzna<Integer> zzbdk = zzna.zza(1, "gads:cache:ad_request_timeout_millis", (int) ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    private static final zzna<Integer> zzbdl = zzna.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static final zzna<Long> zzbdm = zzna.zza(1, "gads:cache:javascript_timeout_millis", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzna<Boolean> zzbdn = zzna.zza(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final zzna<Boolean> zzbdo = zzna.zza(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final zzna<Boolean> zzbdp = zzna.zza(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final zzna<Long> zzbdq = zzna.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzna<Boolean> zzbdr = zzna.zza(1, "gads:cache:use_cache_data_source", (Boolean) false);
    private static final zzna<Boolean> zzbds = zzna.zza(1, "gads:cache:connection_per_read", (Boolean) false);
    private static final zzna<Long> zzbdt = zzna.zza(1, "gads:cache:connection_timeout", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    private static final zzna<Long> zzbdu = zzna.zza(1, "gads:cache:read_only_connection_timeout", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzna<Boolean> zzbdv = zzna.zza(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final zzna<String> zzbdw = zzna.zza(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzna<Integer> zzbdx = zzna.zza(1, "gads:http_assets_cache:time_out", 100);
    public static final zzna<Boolean> zzbdy = zzna.zza(1, "gads:chrome_custom_tabs:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbdz = zzna.zza(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final zzna<Boolean> zzbea = zzna.zza(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final zzna<Boolean> zzbeb = zzna.zza(1, "gads:drx_in_app_preview:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbec = zzna.zza(1, "gads:drx_debug_signals:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbed = zzna.zza(1, "gads:debug_hold_gesture:enabled", (Boolean) false);
    public static final zzna<Long> zzbee = zzna.zza(1, "gads:debug_hold_gesture:time_millis", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzna<String> zzbef = zzna.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzna<String> zzbeg = zzna.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzna<String> zzbeh = zzna.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzna<String> zzbei = zzna.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzna<Integer> zzbej = zzna.zza(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzna<Integer> zzbek = zzna.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzna<Boolean> zzbel = zzna.zza(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final zzna<Boolean> zzbem = zzna.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final zzna<Integer> zzben = zzna.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzna<Boolean> zzbeo = zzna.zza(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final zzna<Boolean> zzbep = zzna.zza(1, "gads:clearcut_logging:write_to_file", (Boolean) false);
    public static final zzna<Boolean> zzbeq = zzna.zza(0, "gad:force_local_ad_request_service:enabled", (Boolean) false);
    public static final zzna<Boolean> zzber = zzna.zza(0, "gad:force_dynamite_loading_enabled", (Boolean) false);
    public static final zzna<Integer> zzbes = zzna.zza(1, "gad:http_redirect_max_count:times", 8);
    public static final zzna<Boolean> zzbet = zzna.zza(1, "gads:omid:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbeu = zzna.zza(0, "gads:nonagon:red_button", (Boolean) false);
    private static final zzna<Boolean> zzbev = zzna.zza(1, "gads:nonagon:banner:enabled", (Boolean) false);
    private static final zzna<String> zzbew = zzna.zza(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static final zzna<Boolean> zzbex = zzna.zza(1, "gads:nonagon:interstitial:enabled", (Boolean) false);
    private static final zzna<String> zzbey = zzna.zza(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static final zzna<Boolean> zzbez = zzna.zza(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbfa = zzna.zza(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) false);
    private static final zzna<String> zzbfb = zzna.zza(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static final zzna<Boolean> zzbfc = zzna.zza(1, "gads:nonagon:nativead:enabled", (Boolean) false);
    private static final zzna<String> zzbfd = zzna.zza(1, "gads:nonagon:nativead:app_name", "(?!)");
    public static final zzna<Boolean> zzbfe = zzna.zza(1, "gads:nonagon:banner:check_dp_size", (Boolean) false);
    private static final zzna<Boolean> zzbff = zzna.zza(1, "gads:nonagon:service:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbfg = zzna.zza(1, "gads:signals:ad_id_info:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbfh = zzna.zza(1, "gads:signals:app_index:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbfi = zzna.zza(1, "gads:signals:cache:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbfj = zzna.zza(1, "gads:signals:doritos:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbfk = zzna.zza(1, "gads:signals:location:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbfl = zzna.zza(1, "gads:signals:network_prediction:enabled", (Boolean) false);
    private static final zzna<Boolean> zzbfm = zzna.zza(1, "gads:signals:parental_control:enabled", (Boolean) false);
    public static final zzna<Long> zzbfn = zzna.zza(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
    public static final zzna<String> zzbfo = zzna.zza(0, "gads:public_beta:traffic_multiplier", MpegFrame.MPEG_VERSION_1_0);
    public static final zzna<Boolean> zzbfp = zzna.zza(1, "gads:real_test_request:enabled", (Boolean) true);
    public static final zzna<Boolean> zzbfq = zzna.zza(1, "gads:real_test_request:render_webview_label", (Boolean) true);
    public static final zzna<Boolean> zzbfr = zzna.zza(1, "gads:real_test_request:render_native_label", (Boolean) true);
    public static final zzna<Integer> zzbfs = zzna.zza(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final zzna<Integer> zzbft = zzna.zza(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
    public static final zzna<Integer> zzbfu = zzna.zza(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    public static final zzna<Integer> zzbfv = zzna.zza(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    private static byte[] zzbfw;

    public static void initialize(Context context) {
        zzaml.zza(context, new zznl(context));
        int intValue = ((Integer) zzkb.zzik().zzd(zzazo)).intValue();
        if (intValue <= 0 || zzbfw != null) {
            return;
        }
        zzbfw = new byte[intValue];
    }

    public static void zza(Context context, int i, JSONObject jSONObject) {
        zzkb.zzii();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzkb.zzij().zza(edit, 1, jSONObject);
        zzkb.zzii();
        edit.commit();
    }

    public static List<String> zzjb() {
        return zzkb.zzij().zzjb();
    }

    public static List<String> zzjc() {
        return zzkb.zzij().zzjc();
    }
}
